name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-ctest-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt install libtbb2-dev
      - run: ls /usr/lib/x86_64-linux-gnu/cmake/TBB
      - run: cmake -DTBB_DIR=/usr/lib/x86_64-linux-gnu/cmake/TBB .
      - run: cmake --build .
      - run: ctest

  checkout-and-ctest-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cmake .
      - run: cmake --build . --config Release
      - run: ctest -C Release
